# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About me
    url: '#about'
    weight: 10
  - name: Bioinformatics
    url: '/gallery/Bioinformatics/'
    weight: 40
  - name: Molecular Biology & Field Work
    url: '/gallery/Wetlab/'
    weight: 50
  - name: Publications
    url: 'https://zenodo.org/search?q=metadata.creators.person_or_org.name%3A%22ANDRES%2C%20QUENTIN%20LUDOVIC%20STEPHANE%22&l=list&p=1&s=10&sort=bestmatch'
    weight: 70
#  - name: Contact
#    url: '#contact'
#    weight: 65
#  - name: Gallery & Highlights
#    url: '/gallery'
#    weight: 30